[package]
name = "capacity-report-desktop"
version = "3.0.0"
description = "CapacityReport desktop shell"
authors = ["NIXEVOL"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
open = "5.3.5"
reqwest = { version = "0.13", default-features = false, features = ["stream"] }
serde = { version = "1", features = ["derive"] }
sysinfo = { version = "0.38.4", default-features = false, features = ["system"] }
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"

[features]
default = []
