[package]
name = "capacity-report-desktop"
version = "2.0.3"
description = "CapacityReport desktop shell"
authors = ["NIXEVOL"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["devtools"] }
tauri-plugin-shell = "2"

[features]
default = []
